<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MM.Domain\MM.Domain.csproj" />
    <ProjectReference Include="..\MM.Application\MM.Application.csproj" />
    <ProjectReference Include="..\MM.Infrastructure\MM.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
